name: Homebrew audit

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  audit:
    runs-on: macos-15
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@3cdb78d0f62ad29dd32de765782654f4eedea607 # 2026.08.31.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check tap syntax
        run: brew test-bot --only-tap-syntax
