name: Homebrew audit

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  audit:
    runs-on: macos-15
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@9af03b7ae3f9e2ae5c174f659d5c3909f7e7dbac # 2026.07.29.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check tap syntax
        run: brew test-bot --only-tap-syntax
