name: Homebrew audit

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  audit:
    runs-on: macos-15
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@b35a29a0f83ee8b8ca07b219fc8db3d7bb88ab49 # 2026.08.10.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check tap syntax
        run: brew test-bot --only-tap-syntax
